default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: alchemist_development

test:
  <<: *default
  database: alchemist_test

production:
  <<: *default
  database: alchemist_production
  username: alchemist
  password: <%= ENV['ALCHEMIST_DATABASE_PASSWORD'] %>
